version: '3.8'

services:
  vn-buyer-guide:
    build:
      context: .
      dockerfile: Dockerfile
      target: production  
    
    container_name: vn-buyer-guide-fe
    
    ports:
      - "3000:3000"
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
