export const REGION_KEYS_BY_COUNTRY: Record<string, readonly string[]> = {
  vietnam: [
    "hanoi",
    "hcm",
    "haiphong",
    "danang",
    "cantho",
    "hue",
    "angiang",
    "bacninh",
    "camau",
    "caobang",
    "dienbien",
    "daklak",
    "dongnai",
    "dongthap",
    "gialai",
    "hatinh",
    "hungyen",
    "khanhhoa",
    "laichau",
    "langson",
    "laocai",
    "lamdong",
    "nghean",
    "ninhbinh",
    "phutho",
    "quangngai",
    "quangninh",
    "quangtri",
    "sonla",
    "tayninh",
    "thainguyen",
    "thanhhoa",
    "tuyenquang",
    "vinhlong",
    "binhduong",
    "other-region",
  ],
}

export const COUNTRY_NONE = "__none__"
